sites:
    alienvault:
        site: otx.alienvault.com/taxii
        discovery_path: /discovery
        collection_management_path: /collections
        poll_path: /poll
        use_https: True
        ssl_verify: False
        cert_file:
        key_file:
        default_score:
        username: 0dd92ced56580311a769a496cd1fa72533f7b5d1f4c1b1b6aa7a35425baa97f6
        password: ignored
        collections: user_AlienVault
        start_date: 2019-10-30 00:00:00
        minutes_to_advance: 1440
        ca_cert:
        http_proxy_url:
        https_proxy_url:
        reports_limit: 100
        fail_limit: 10
