sites:
    alienvault:
        feed_id: 
        site: otx.alienvault.com/taxii
        discovery_path: /discovery
        collection_management_path: /collections
        poll_path: /poll
        use_https: True
        ssl_verify: False
        cert_file:
        key_file:
        default_score: 5
        username:
        password:
        collections: user_AlienVault
        start_date: 2019-10-30 00:00:00
        minutes_to_advance: 1440
        ca_cert:
        http_proxy_url:
        https_proxy_url:
        reports_limit: 10000
        fail_limit: 10
